version: '3.10'

services:
  cosmosdb_emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:mongodb
    container_name: cosmosdb_emulator
    ports:
      - "10250:10250"
      - "10251:10251"
      - "27017:27017"
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 2
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    volumes:
      - cosmosdb_data:/data/cosmosdb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - cosmosdb_emulator
    environment:
      - MONGO_URI=mongodb://cosmosdb_emulator:27017
      - MONGO_DB=mydatabase
      - PYTHONPATH=/app

volumes:
  cosmosdb_data:
